### ISSUE TITLE
Implement volume in Dockerfile

### ISSUE THREAD

**Issue by AaronLionsheep** [JonathanDygert/blabber#1]
The Dockerfile copies the contents into the container, but changes to the app on the host do not reflect in a running container.

**Comment by jdygert** [comment]
The current app is stateless anyways, and once it does have state I think that'll just be with a database which will be in another image managed by docker-compose, so we can set a volume in that once we get there.

**Comment by AaronLionsheep** [comment]
In all of his demos, he used the -v option to mount the code on his machine into the container so that he could edit it live. In the slides for the project, he includes:
```
FROM python:alpine
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
CMD ["flask", "run", "--host=0.0.0.0"]
```
and shows it being run with
```
$ docker build -t python-with-flask .
$ docker run -p 5000:5000 \
    -v ${PWD}/src:/app/src \
    -e FLASK_APP=src/app.py \
    -e FLASK_ENV=development \
    python-with-flask
```

I remember him mentioning at the end that this is basically the entire milestone right here, except getting the volume part from the command line directly into the Dockerfile.

There isn't any specific mention of this though...

**Comment by jdygert** [comment]
Yeah, but I think the main Dockerfile should only have what you need to "deploy" your app. We're already set for the first milestone, this is all we need for it. I built and ran like the assignment says:

```
build -t python-app .
docker run -p 5000:5000 python-app
curl localhost:5000/greetings
```

You're right for live editing that you need a volume or bind mount. Do you use VSCode? I use their extension that lets you easily set up using docker for development.

**Comment by AaronLionsheep** [comment]
Yeah, I had thought the same, but I just remembered him mentioning that bit at the very end. The volumes usually go in a docker-compose config.

I pretty much just use vi for stuff like this. I have been forced to use vi for all programming at my internship, so no amenities for me...

**Comment by jdygert** [comment]
I like vim for just editing files but prefer VSCode for actual projects. I use vim keybindings for VSCode though lol.
